name: S2S
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies: 
  - matplotlib
  - numpy
  - xarray
  - basemap
  - netcdf4
  - python
  - ipython
  - cartopy
  - spyder
  - ecmwf-api-client
  - properscoring
  - scipy
  - cdo
  - xesmf 
  - seaborn
  - cfgrib
  - xarray-extras

#installed manually:
# pip3 install gridpp==0.6.0-dev.1

